# Generated by Django 4.0 on 2021-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='position',
            field=models.CharField(default='Developer', max_length=255),
            preserve_default=False,
        ),
    ]
